<a href="https://colab.research.google.com/github/MarouaneAyech/IA_24_25/blob/main/tp_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Classification**

## Collecte des données

Les données concernent des employés d'une entreprise.

Les informations des employés collectées sont l'age et le salaire.

Les données sont representées sous la forme d'une matrice.

Les lignes correspondentles individus (employés).

Les colonnes sont les informations (variables).

Pour pouvoir classifier les employés, on a besoin d'une information supplémentaire, qui représente l'étiquette ou la classe. Elle prend une de deux valeurs : Junior ou Senior

Cette information est représentée comme étant un vecteur qui contient les classes des employés (de la matrice).

In [20]:
import numpy as np
X_train = np.array([[25,1200], # 1ere ligne
              [28,1500], # 2eme ligne
              [45,2500],
              [42,2100],
              [30,1600],
              [51,3000]]
             )

In [21]:
X_train

array([[  25, 1200],
       [  28, 1500],
       [  45, 2500],
       [  42, 2100],
       [  30, 1600],
       [  51, 3000]])

In [22]:
# Etiquettes/labels des classes
# Junior : 0
# Senior : 1
y_train=np.array([0,0,1,1,0,1])

In [23]:
y_train

array([0, 0, 1, 1, 0, 1])

## Choix du modèle (Regression Logistique) et des hyperparamètres

In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
model=LogisticRegression()

## Apprentissage

In [26]:
model.fit(X_train,y_train)

LogisticRegression()

## Affichage des paramètres du modèle (poids & intercept)

In [27]:
model.coef_

array([[0.00085403, 0.03796021]])

In [28]:
model.intercept_

array([-70.26575774])

## Prediction des classes pour les données de test

In [29]:
X_test = np.array([[30,1600], # 1ere ligne
                  [24,1100], # 2eme ligne
                  [50,3000],
                  [40,1900]]
                )

In [30]:
y_test=np.array([0,0,1,1])

In [31]:
y_test_pred=model.predict(X_test)

In [32]:
y_test_pred

array([0, 0, 1, 1])

## Evaluation du modèle

In [33]:
from sklearn.metrics import accuracy_score

In [34]:
accuracy_score(y_test,y_test_pred)

1.0

In [35]:
from sklearn.metrics import confusion_matrix

In [36]:
confusion_matrix(y_test,y_test_pred, labels=[0,1])

array([[2, 0],
       [0, 2]])