<a href="https://colab.research.google.com/github/MarouaneAyech/IA_24_25/blob/main/tp3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Regression**

## Collecte des données

Les données concernent des employés d'une entreprise.

Les informations des employés collectées sont l'age et le salaire.

Les données sont representées sous la forme d'une matrice.

Les lignes correspondentles individus (employés).

Les colonnes sont les informations (variables).

Pour assurer la prédiction de primes des employés, on a besoin des valeurs des primes des employés ci-dessus.

In [ ]:
import numpy as np
X_train = np.array([[25,1200], # 1ere ligne
              [28,1500], # 2eme ligne
              [45,2500],
              [42,2100],
              [30,1600],
              [51,3000]]
             )

In [ ]:
X_train

array([[  25, 1200],
       [  28, 1500],
       [  45, 2500],
       [  42, 2100],
       [  30, 1600],
       [  51, 3000]])

In [ ]:
# Etiquettes/labels (primes)
y_train=[100,150,500,600,200,800]

In [ ]:
y_train

[100, 150, 500, 600, 200, 800]

## Choix du modèle (Regression Lineaire) et des hyperparamètres

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model=LinearRegression()

## Apprentissage

In [ ]:
model.fit(X_train,y_train)

LinearRegression()

## Affichage des paramètres du modèle (poids & intercept)

In [ ]:
model.coef_

array([38.20626426, -0.1896166 ])

In [ ]:
model.intercept_

-639.5244779785924

## Prediction des primes pour les données de test

In [ ]:
X_test = np.array([ [29,1550], # 2eme ligne
                    [43,2600],
                    [40,2200],
                    [31,1610]]
                )

In [ ]:
y_test=np.array([160,510,590,210])

In [ ]:
y_test_pred=model.predict(X_test)

In [ ]:
y_test_pred

array([174.5514564 , 510.34172662, 471.56957361, 239.58698895])

## Evaluation du modèle

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
mean_squared_error(y_test,y_test_pred)

3778.2543675593915

In [ ]:
r2_score(y_test,y_test_pred)

0.89022685694398